- name : Install and run nginx
  hosts: web
  become: yes
  tasks:
  - name : install
    ansible.builtin.package:
     name: iginx
     status: present
  - name : start nginx 
    ansible.builtin.service:
     name: start nginx
     status: started 
     enabled: yes   
