- name: filters
  hosts: local
  connection: local
  tasks:
  - name: undefine variable 
    ansible.builtin.debug:
      msg: "Helo {{ person | default (' Rida Tahani ')}}"
  
  - name: converting to string to list
    vars:
      names: " Sanaulla, Heera, Rida, Raees "
    ansible.builtin.debug:
      msg: " Names are: {{ names | split(',') }}"

  - name: converting map into list
    vars:
      person_info: 
        Name: Sanaulla
        Age: 35 
        Address: kothakoya
    ansible.builtin.debug:
      msg: " person details: {{ person_info | dict2items }}" 
      
  - name: print min and max
    vars:
      numbers: [1,45,6,888,543]
    ansible.builtin.debug:
      msg: " min is: {{ numbers | min }}, max is : {{numbers | max }} " 

  - name: Valid ip address
    vars:
      ip: "121.134.11.6"
    ansible.builtin.debug:
      msg: "{{ ip |ansible.utils.ipaddr }}"        