- name: Variable
  hosts: local
  connection: local
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: " Corse is {{ COURSE }} , Duration is {{ DURATION }}, trainer is {{ TRAINER }}"