- name : install and start nginx
  hosts: web
  becomes: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes