- name: Variable
  hosts: local
  connection: local
  vars: # PLAY level Veriable ,global varable
   COURSE: "Devops with AWS"
   DURATION: 120days
   TRAINER: Sanaulla
  tasks:
  - name: print the variables
    vars: # task level variable 
     COURSE: "Ansible"
    ansible.builtin.debug:
      msg: " Corse is {{ COURSE }} , Duration is {{ DURATION }}, trainer is {{ TRAINER }}"

  - name: print the variables
    ansible.builtin.debug:
      msg: " Corse is {{ COURSE }} , Duration is {{ DURATION }}, trainer is {{ TRAINER }}"